name: deployment

# Only when pushing to master
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Send a webhook to Hoplite
        uses: distributhor/workflow-webhook@v1.0.2
        env:
          webhook_auth: ${{ secrets.webhook_auth }}
          webhook_secret: ${{ secrets.webhook_secret }}
          webhook_url: ${{ secrets.webhook_url }}
          data: '{"service": "tellurianband.com"}'
